version: "3.1"

services:
  nginx-proxy:
    image: nginx-proxy:dev
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - nginx-proxy-network
networks:
  nginx-proxy-network:
    external: true